### ISSUE TITLE
#ehancement: Is it possible to add the generator for C89 (ansi C)?

### ISSUE THREAD

**Issue by katte** [thradams/cake#5]

**Comment by thradams** [comment]
I added few transformations for C89, but it is an starting point.. 
I converted _Bool to int. Maybe I will change to char. Also nullptr, true and false. And //comments to /*comments*/

The feature I think is important to translate is compound literal because having a C89 version of it makes the code compatible with C++. (In case someone wants to use a C++ compiler)

I also will need to make compound literals declared because C23 added storage modifiers like (static) for
compound literals. So to translate this to <C23 I will have to do the same job.

**Comment by thradams** [comment]
I will close this item and when necessary we can open individual requests for C89. 
Does anyone have a particular request?

The next one will be C99 compound literal to C89.
